#cloud-config

coreos:

  units:
  - name: droplan-setup.service
    command: start
    content: |
      [Unit]
      Description=setup droplan iptable rules for docker

      [Service]
      Type=oneshot
      After=docker.service
      ExecStart=/usr/bin/sh -c "docker ps; \
        iptables -N droplan-peers; \
        iptables -I FORWARD 1 -i eth1 -j DROP; \
        iptables -I FORWARD 1 -i eth1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT; \
        iptables -I FORWARD 1 -j droplan-peers"

  - name: droplan.service
    command: start
    content: |
      [Unit]
      Description=updates iptables with peer droplets
      After=droplan-setup.service
      Requires=docker.service

      [Service]
      Type=oneshot
      Environment=DO_KEY=
      Environment=DO_TAG=trubthumping
      ExecStart=/usr/bin/docker run --rm --net=host --cap-add=NET_ADMIN -e DO_KEY -e DO_TAG tam7t/droplan:latest

  - name: droplan.timer
    command: start
    content: |
      [Unit]
      Description=Run droplan.service every 5 minutes

      [Timer]
      OnCalendar=*:0/5

  - name: trubthumping-volume.service
    command: start
    content: |
      [Unit]
      Description=Trubthumping Volumes
      Requires=docker.service
      After=docker.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run -i --name trubthumping-volumes jspc/trubthumping-volumes
      ExecStop=/usr/bin/docker stop -t 2 trubthumping-volumes
      ExecStopPost=/usr/bin/docker rm -f trubthumping-volumes

      [Install]
      WantedBy=default.target

  - name: trubthumping-theme.service
    command: start
    content: |
      [Unit]
      Description=Trubthumping Blog Theme
      Requires=docker.service
      After=docker.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run -i --name trubthumping jspc/trubthumping
      ExecStop=/usr/bin/docker stop -t 2 trubthumping
      ExecStopPost=/usr/bin/docker rm -f trubthumping

      [Install]
      WantedBy=default.target

  - name: ghost.service
    command: start
    content: |
      [Unit]
      Description=Ghost Blog
      Requires=docker.service trubthumping-theme.service trubthumping-volume.service
      After=docker.service trubthumping-theme.service trubthumping-volume.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run --name ghost \
                                    --volumes-from=trubthumping-volumes  \
                                    --volumes-from=trubthumping \
                                    -e NODE_ENV=production \
                                    -e GHOST_DATABASE_PASSWORD=ghostpassword \
                                    -e MYSQL_PORT_3306_TCP_ADDR=10.131.27.93 \
                                    -e MYSQL_PORT_3306_TCP_PORT=3306 \
                                    ghost

      ExecStop=/usr/bin/docker stop -t 2 ghost
      ExecStopPost=/usr/bin/docker rm -f ghost

      [Install]
      WantedBy=default.target

  - name: ghost-proxy.service
    command: start
    content: |
      [Unit]
      Description=Haproxy and TLS Termination for ghost
      Requires=docker.service ghost.service
      After=docker.service ghost.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run -p 0.0.0.0:80:80 \
                                    -p 0.0.0.0:443:443 \
                                    -v /ssl:/ssl \
                                    -e HAPROXY_USERNAME=foo \
                                    -e HAPROXY_PASSWORD=bar \
                                    --link ghost:ghost \
                                    --name=proxy \
                                    jspc/ghost-proxy

      ExecStop=/usr/bin/docker stop -t 2 proxy
      ExecStopPost=/usr/bin/docker rm -f proxy

      [Install]
      WantedBy=default.target
